### PR TITLE
Visual bugs fixes

### LINKED ISSUE #47: Firefox mobile view menu opener
On Menu opener - content overlaps with background image

Screen Shot 2020-06-08 at 2 38 11 PM

### PR DESCRIPTION
**Pull request by IanKBovard**
closes #47 #45 #50 #44

### CODE REVIEW

File: src/components/Card/ScheduleCard.js [hunk 1]
```diff
@@ -20,13 +20,13 @@ const ScheduleCard = ({
...
         minWidth: '336px',
-        maxHeight: '100%',
+        height: '100%',
         maxWidth: '576px',
       }}
       round="medium"
       overflow="hidden"
     >
-      <Box direction="column">
+      <Box direction="column" className="HELLO ONE">
```
Comment (britt6612) [inline src/components/Card/ScheduleCard.js:29]: should we take these out ? Im guessing you were just inspecting and searching for classNames

Comment (IanKBovard) [reply src/components/Card/ScheduleCard.js:29]: woops

Comment (IanKBovard) [reply src/components/Card/ScheduleCard.js]: done
